name: Sigrid pull request feedback
on: [pull_request]

jobs:
  sigridci:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    steps:
      - name: Check out repository
        uses: actions/checkout@v7
        with:
          fetch-depth: 0
      - name: Sigrid CI
        uses: Software-Improvement-Group/sigridci@consolidated-feedback
        with:
          customer: sigdelivery
          system: sigrid-ci-example-dennis
          capability: maintainability,osh,security,architecture
        env:
          SIGRID_CI_TOKEN: "${{ secrets.SIGRID_CI_TOKEN }}"
          SIGRIDCI_GITHUB_COMMENT_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
      - name: Save Sigrid CI results
        uses: actions/upload-artifact@v4
        if: always()
        with:
         name: sigrid-ci-output
         path: "sigrid-ci-output/**"
         
